<a href="https://colab.research.google.com/github/jkarya/almabetter_project/blob/main/practic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
add= lambda x,y : x+y
result = add(3,4)
print(result)

7


In [ ]:
def add1(x,y):
  z = x+y
  return z
result= add1 (6,4)
print(result)

10


In [ ]:
divide= lambda x,y: "undefine" if y==0 else x//y

In [ ]:
print(divide(10,2))

5


In [ ]:
numbers=[1,2,3,4,5,6,7,8,9,10]
even_numbers=list(filter(lambda x:x%2==0,numbers))
print(even_numbers)

[2, 4, 6, 8, 10]


In [ ]:
def even_num(x):
  lst=[]
  for num in x:
    if num %2==0:
      lst.append(num)
  return lst
numbers =[1,2,3,4,5,6,7,8,9,10]
lst= even_num(numbers)
lst


[2, 4, 6, 8, 10]

In [ ]:
numbers =[1,2,3,4,5]
square =list(map(lambda x:x**2,numbers))
print(square)

[1, 4, 9, 16, 25]


In [ ]:
words=["apple","banana","cherry"]
lengths= list(map(len,words))
print(lengths)

[5, 6, 6]


In [ ]:
square =[]
for i in range(1,11):
  square.append(i**2)
print(square)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
squares=[i**2 for i in range (1,11) if i%2==0]
print(squares)

[4, 16, 36, 64, 100]


In [ ]:
pairs=[(i,j)for i in range (1,6) if i%2==0 for j in range(1,6)if j%2==1]
print(pairs)

[(2, 1), (2, 3), (2, 5), (4, 1), (4, 3), (4, 5)]


In [ ]:
grades=[78,92,85,65,89,76,81]
lst=[]
for grade in grades:
  if grade>=90:
    lst.append("A")
  elif grade >=80:
    lst.append("C")
  elif grade >= 70:
    lst.append("D")
  elif grade >=60:
    lst.append("D")
  else:
    lst.append("E")

lst

['D', 'A', 'C', 'D', 'C', 'D', 'C']

In [ ]:
print(['A'if grade >=90 else 'B' if grade >=80 else 'C' if grade >=70 else 'D'if grade>60 else'F' for grade in grades])

['C', 'A', 'B', 'D', 'B', 'C', 'B']


In [ ]:

prices=[100,50,80,120,150]
lst=[]
for price in prices:
  lst.append(price*0.8)
print(lst)

[80.0, 40.0, 64.0, 96.0, 120.0]


In [ ]:
print([price*0.8 for price  in prices])

[80.0, 40.0, 64.0, 96.0, 120.0]


In [ ]:
vowels =set()
for  char in "hello world":
  if char in "aeiou":
    vowels.add(char)
print(vowels)

{'o', 'e'}


In [ ]:
voels=[char for char in "hello world" if char in "aeiou"]
print(vowels)

{'o', 'e'}


In [ ]:
string1="hello"
string2="world"
unique_chars ={char for char in string1 for char2 in string2 if char==char2}
print(unique_chars)


{'l', 'o'}


In [ ]:
class calculator:
 def __init__(self):
    self.result=0
 def add(self,num1,num2):
     self.result= num1+num2
     return self.result
 def subtraction (self,num1,num2):
     self.result= num1-num2
     return self.result
 def multiply(self,num1,num2):
     self.result= num1*num2
     return self.result
 def divide(self,num1,num2):
     if num2==0:
      raise ValueError("cannot divide by zero")
     self.result= num1/num2
     return self.result
 def clear(self):
     self.result=0
     return self.result


In [ ]:
result=9

In [ ]:
class Atm:
# constructure
  def __init__(self):
   self. pin=''
   self. balance=0
   self. menu()

  def menu(self):
    user_input =input("""
    hHi how can i help you?
    1.Press 1 to creat pin
    2.Press 2 to change pin
    3.Press 3 to check balance
    4.Press 4 to withdraw
    5. Anything else to exit
    """)
    if user_input=='1':
      #create pin
      self.create_pin()
    elif user_input=='2':
      #change ppin
      self.change_pin()
    elif user_input=='3':
      #check balance
      self.check_balance()
    elif user_input=='4':
      #withdraw
      self.withdraw
    else:
      exit()
  def create_pin(self):
   user_pin=input('enter your pin')
   self.pin =user_pin
   user_balance=int(input('enter balance'))
   self.balance=user_balance

   print('pin creatrd succcessfully')
   self.menu()
  def change_pin(self):
    old_pin=input('enter old pin')
    if old_pin==self.pin:
     new_pin=input('enter new pin')
     self.pin=new_pin
     print('pin change successfully')
     self.menu()
    else:
      print('nai karna h ha chNAGE')
      self.menu()
  def check_balance(self):
    user_pin=input('enter your pin')
    if user_pin == self.pin:
      print('ypur balance is',self.balance)
    else:
     print('chal nikal')
    self.menu()
  def withdraw(self):
    user_pin=input('enter the pin')
    if user_pin== self.pin:
     amount=int( input('enter the amount'))
     if amount<=self.balance:
      self.balance=self.balance-amount
      print('withdraw successful balance is ',self.balance)
     else:
      print('abe garib')
    else:
      print('sale chore')
    self.menu()

In [ ]:
obj=Atm()


    hHi how can i help you?
    1.Press 1 to creat pin
    2.Press 2 to change pin
    3.Press 3 to check balance
    4.Press 4 to withdraw
    5. Anything else to exit
    1
enter your pin1234
enter balance10000
pin creatrd succcessfully

    hHi how can i help you?
    1.Press 1 to creat pin
    2.Press 2 to change pin
    3.Press 3 to check balance
    4.Press 4 to withdraw
    5. Anything else to exit
    2
enter old pin1234
enter new pin2345
pin change successfully

    hHi how can i help you?
    1.Press 1 to creat pin
    2.Press 2 to change pin
    3.Press 3 to check balance
    4.Press 4 to withdraw
    5. Anything else to exit
    3
enter your pin2345
ypur balance is 10000


In [ ]:
my_array=[]

In [ ]:
my_array=[1,2,3,4,5]

In [ ]:
import array
my_array=array.array('i',[1,2,3,4,5])
my_array

array('i', [1, 2, 3, 4, 5])

In [ ]:
import numpy as np
my_array=np.array([[1,2,3],[4,5,6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
my_array=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#class and section [[1A,1B,2C],[2A,2B,c],[3A,3B,3C],[4A,4B,4C]]
class_size=[[25,30,28],
            [20,22,25],
            [27,24,26],
            [18,20,22]]



In [ ]:
print(class_size[0][0])
print(class_size[2][1])
print(class_size[3][2])

sum_1=0
for i in range(0,len(class_size)):
  sum_1= sum_1+sum(class_size[i])
  print('the strength of class',i+1,'is',sum(class_size[i]))

print('the strength of scholl is ', sum_1)

25
24
22
the strength of class 1 is 83
the strength of class 2 is 67
the strength of class 3 is 77
the strength of class 4 is 60
the strength of scholl is  287


In [ ]:
my_array=[1,2,3,4,5]
search_element = 3

for index,element in enumerate(my_array):
  if element ==search_element:
    print('Element found at index: ', index)
    break
else:
  print('Element not found in the array')


Element found at index:  2


In [ ]:
arr=[]
arr.append(10)
arr.append(20)
arr.append(30)
arr.insert(1,15)
print(arr)

[10, 15, 20, 30]


In [ ]:
arr=[10,15,20,25,30]
del arr[2]
arr.remove(30)
print(arr)


[10, 15, 25]


In [ ]:
arr=[10,15,20,25,30]
arr.sort()
print(arr)
arr.sort(reverse=True)
print(arr)

[10, 15, 20, 25, 30]
[30, 25, 20, 15, 10]


In [ ]:
arr=[1,2,3,4,5]
print(arr[2])

3


In [ ]:
menus=[
    ['Burger',10.9,'Entree'],
    ['Salad',7.99,'Appetizer'],
    ['pizza',14.99,'entree'],
    ['fries',3.99,'side'],
    ['ice cream',4.99,'Dissert'],
]


In [ ]:
list_item=[]
for menu in menus:
 list_item.append(menu[0])
list_item

['Burger', 'Salad', 'pizza', 'fries', 'ice cream']

In [ ]:
search_item=input('Enter a menu item to search: ')
if search_item in list_item:
  print('Item in menu')
else:
  print('item not found')


Enter a menu item to search: mosns
item not found


In [ ]:
menus.sort(key=lambda item:item[1])
menus

[['fries', 3.99, 'side'],
 ['ice cream', 4.99, 'Dissert'],
 ['Salad', 7.99, 'Appetizer'],
 ['Burger', 10.9, 'Entree'],
 ['pizza', 14.99, 'entree']]

In [ ]:
delet_item=input('Enter a menu item to  delet: ')
for menu in menus:
  if menu[0]== delet_item:
    menus.remove(menu)
    break
  else:
    print('Menu item not found')
menus




Enter a menu item to  delet: pizza
Menu item not found
Menu item not found
Menu item not found
Menu item not found


[['fries', 3.99, 'side'],
 ['ice cream', 4.99, 'Dissert'],
 ['Salad', 7.99, 'Appetizer'],
 ['Burger', 10.9, 'Entree']]

In [ ]:
string1='Hellow'
string2='World'
concatenated_string=string1+' '+string2
print(concatenated_string)
string_list=['apple','banana','orange']
separator=','
concatenated_string=separator.join(string_list)
print(concatenated_string)

Hellow World
apple,banana,orange


In [ ]:
from array import array
arr=array('i',[1,2,3])
print(arr[0])

1


In [ ]:
value=230
if value>112:
  print(value)
  value+=1

230


In [ ]:
if 10 in [0,10,20]:
  print('yes')

yes


In [ ]:
def facto(n):
  if n==1:
    return 1
  else:
    return n*facto(n-1)
facto(5)

120

In [ ]:
import math
print(math.factorial(5))

120


In [ ]:
def calculate_point(items):
  if items==1:
    return 1
  else:
    return items +calculate_point(items-1)
calculate_point(6)

21

In [ ]:
def factorial(n):
  if n==1:
    return 1
  else:
    return  n* factorial(n-1)
factorial(5)

120

In [ ]:
def fact(n):
  result=1
  for i in range (1, n+1):
    result=result*i
    #print(result)
  return result
fact(6)

720

In [ ]:
def fib(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fib(n-2)+fib(n-1)
fib(4)

3

In [ ]:
string='leveel'
if string == string[ : :-1]:
  print('Palindrome')
else:
  print('Not Palindrom')

Not Palindrom


In [ ]:
def is_palindrom(string):
  if len(string)<2:
    return True
  if string[0]!=string[-1]:
    return False
  return is_palindrom(string[1:-1])

In [ ]:
is_palindrom('level')

True

In [ ]:
if is_palindrom('leevel'):

 print('Palindrome')
else:
  print('Not Palindrome')


Not Palindrome


In [ ]:
%%time
def factorial(n):
  if n==0:
    return 1
  else:
    return n*factorial(n-1)
factorial(5)

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 32.2 µs


120

In [ ]:
%%time
def factorial(n):
  if n==0:
    return 1
  else:
    return n*factorial(n-1)
factorial(10)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 37.9 µs


3628800

In [ ]:
def display_reverse(arr,index):
  if index<0:
    return
  else:
    print(arr[index])
    display_reverse(arr,index-1)

In [ ]:
my_array=[1,2,3,4,5]
display_reverse(my_array,3)

4
3
2
1


In [ ]:
indx=2
for i in range(0,indx+1):
  print(my_array[indx-1])

2
2
2


# ***module 2***

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.array([1,2,3,4,5])
df= pd.DataFrame({'Name':['Alice','Bob','Charlie'],'Age':[25,30,35]})

In [ ]:
print(arr[2])
print(arr[0])

3
1


In [ ]:

print(sum(arr))
mean=sum(arr)/len(arr)
print(mean)

15
3.0


In [ ]:
np.mean(arr)

3.0

In [ ]:
np.median(arr)

3.0

In [ ]:
import numpy as np
arr=np.random.randint(0,100,size=10)
arr_sorted=np.sort(arr)
print(arr)
print(arr_sorted)

[29 67 73 71 91 43 58 24 29 73]
[24 29 29 43 58 67 71 73 73 91]


In [ ]:
arr=np.array([1,2,3,4,5])
arr_squared=arr**2
arr_sum=np.sum(arr)
arr_mean = np.mean(arr)

print(arr)
print(arr_squared)
print(arr_sum)
print(arr_mean)

[1 2 3 4 5]
[ 1  4  9 16 25]
15
3.0


In [ ]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [ ]:
import numpy as np
my_array= np.array([1,2,3,4,5])
my_2d_arrya= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_array)
print(my_2d_arrya)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.std(my_array)

1.4142135623730951

In [ ]:
arr=np.arange(10)
print(arr)
arr2=np.arange(5,10,2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[5 7 9]


In [ ]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr1d=np.arange(10)
print(arr1d)
arr2d=arr1d.reshape(2,5)
arr2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1d.resize(2,5)
arr1d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
arr_transpose= np.transpose(arr2d)
print(arr_transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1d=arr_2d.flatten()
print(arr_2d)
print(arr_1d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
arr2d= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
row1=arr2d[0,:]
print(row1)
col2=arr2d[ :,1]
print(col2)
subarr=arr2d[1:3,0:2]
print(subarr)

[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]


In [ ]:
arr3d=np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])
mat1=arr3d[0, : ,:]
print(mat1)
col2=arr3d[0, : ,:]
print(col2)
subarr=arr2d[1:3,0:3]
print(subarr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, [4, 5])
print(new_arr)

[1 4 5 2 3]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.transpose(arr)
print(new_arr)

[[1 3]
 [2 4]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.reshape(arr, (2, 3))
print(new_arr)




[[1 2 3]
 [4 5 6]]
